### ISSUE TITLE
int8推理时间与表格不同

### ISSUE THREAD

**Issue by genius0182** [CodeGeeX/codegeex-fastertransformer#10]
您好：
     我们用的参数除了data_type改成int8其他参数不变，使用python3 post.py在单卡A100上测试为15s。不是表格中的3.1s。这是什么原因呢。

**Comment by genius0182** [comment]
是在阿里云上测试的。

**Comment by Stanislas0** [comment]
您好！这个commit应该修复了相关问题，可以重新编译再试一下：https://github.com/CodeGeeX/codegeex-fastertransformer/commit/8bf9f0a0af6a24d31bf20ad69087e543a9821dde

**Comment by genius0182** [comment]
done

**Comment by chanjetsdp** [comment]
> 您好： 我们用的参数除了data_type改成int8其他参数不变，使用python3 post.py在单卡A100上测试为15s。不是表格中的3.1s。这是什么原因呢。

你用的什么配置的服务器？ 有比较详细的部署文档吗？ 谢谢 @genius0182
