### ISSUE TITLE
torch.classes.load_library("libth_codegeex.so")报错

### ISSUE THREAD

**Issue by cdj0311** [CodeGeeX/codegeex-fastertransformer#3]
你好，
我编译这个仓库后使用torch.classes.load_library("libth_codegeex.so")会报以下错误：
````
/data/codegeex-fastertransformer/build/lib/libth_codegeex.so: undefined symbol: _ZN17fastertransformer16ParallelCodegeexIfE7forwardEPSt13unordered_mapISsNS_6TensorESt4hashISsESt8equal_toISsESaISt4pairIKSsS3_EEEPKSC_PKNS_22ParallelCodegeexWeightIfEE
````
而在相同环境下直接使用nvidia/fastertransformer编译后加载libth_gpt.so等库就没有问题，请问这是怎么回事？

**Comment by Stanislas0** [comment]
您好，请问编译时是否在``make_all.sh``中指定了显卡对应的DSM版本？
https://github.com/CodeGeeX/codegeex-fastertransformer/blob/main/make_all.sh#L5

**Comment by cdj0311** [comment]
> 您好，请问编译时是否在`make_all.sh`中指定了显卡对应的DSM版本？ https://github.com/CodeGeeX/codegeex-fastertransformer/blob/main/make_all.sh#L5

指定了的

**Comment by merlinarer** [comment]
我也遇到相同的问题，在nvcr.io/nvidia/pytorch:21.11-py3中编译没问题，但是在triton中编译就有undefined symbol这个问题，，很奇怪
